behaviors:
  HarvestEliminationBehaviour:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.0002
      beta: 0.005
      epsilon: 0.15
      lambd: 0.95
      num_epoch: 5
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      vis_encode_type: nature_cnn
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        gamma: 0.99
        strength: 0.02
        network_settings:
          hidden_units: 512
        learning_rate: 0.0003
    keep_checkpoints: 10
    max_steps: 500000
    time_horizon: 256
    summary_freq: 100000
    # device: cuda

  ResetAgentBehaviour:
    trainer_type: ppo
    hyperparameters:
      learning_rate: 0.0
    network_settings:
      normalize: false
      hidden_units: 2
      num_layers: 1
      vis_encode_type: simple
    keep_checkpoints: 5
    max_steps: 500000
    time_horizon: 64
    summary_freq: 1000000
    threaded: false
