behaviors:
  HarvestEliminationBehaviour:
    trainer_type: sac
    hyperparameters:
      learning_rate: 0.0003
      learning_rate_schedule: constant
      batch_size: 256
      buffer_size: 2048
      buffer_init_steps: 0
      tau: 0.005
      steps_per_update: 10.0
      save_replay_buffer: false
      init_entcoef: 0.05
      reward_signal_steps_per_update: 10.0
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 1
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        gamma: 0.99
        strength: 0.02
        network_settings:
          hidden_units: 512
        learning_rate: 0.0003
    keep_checkpoints: 5
    max_steps: 2000000
    time_horizon: 128
    summary_freq: 10000
    threaded: false
  
  ResetAgentBehaviour:
    trainer_type: ppo
    hyperparameters:
      learning_rate: 0.0
    network_settings:
      normalize: false
      hidden_units: 2
      num_layers: 1
      vis_encode_type: simple
    keep_checkpoints: 5
    max_steps: 2000000
    time_horizon: 64
    summary_freq: 1000000
    threaded: false
